import { beforeEach, describe, expect, test } from "bun:test";

(globalThis as unknown as { DEBUG_MODE: boolean }).DEBUG_MODE = false;

const {
  getLocalDropoutSubtitles,
  getTranslatedDropoutSubtitles,
  translateVtt,
} = await import("../src/subtitles/dropoutTranslation");

const translateCalls: { texts: string[]; from: string; to: string }[] = [];
let translateImpl = async (texts: string[], _from: string, to: string) =>
  texts.map((text) => `{${to}}${text.toUpperCase()}`);
const fakeTranslate = async (texts: string[], from: string, to: string) => {
  translateCalls.push({ texts, from, to });
  return translateImpl(texts, from, to);
};

const fetchCalls: string[] = [];
let fetchText = "";
const deps = {
  translate: fakeTranslate,
  fetchText: async (url: string) => {
    fetchCalls.push(url);
    return fetchText;
  },
};

const VTT = [
  "WEBVTT",
  "",
  "1",
  "00:00:01.000 --> 00:00:02.000",
  "BRENNAN: Hello <i>world</i>",
  "- [laughs] okay",
  "",
  "00:00:03.000 --> 00:00:04.000 align:start",
  "(SAM) What?",
  ">> ALLY LEE: Yes.",
  "",
  "NOTE not a cue line",
  "",
  "01:00:05.000 --> 01:00:06.000",
  "<c.yellow>plain</c> text",
  "",
].join("\n");

const TRANSLATED_VTT = [
  "WEBVTT",
  "",
  "1",
  "00:00:01.000 --> 00:00:02.000",
  "BRENNAN: {ru}HELLO <i>WORLD</i>",
  "- [laughs] {ru}OKAY",
  "",
  "00:00:03.000 --> 00:00:04.000 align:start",
  "(SAM) {ru}WHAT?",
  ">> ALLY LEE: {ru}YES.",
  "",
  "NOTE not a cue line",
  "",
  "01:00:05.000 --> 01:00:06.000",
  "{ru}<c.yellow>PLAIN</c> TEXT",
  "",
].join("\n");

const vimeoSubtitle = (language: string, url: string) => ({
  source: "vimeo",
  format: "vtt" as const,
  language,
  url,
});

beforeEach(() => {
  translateCalls.length = 0;
  fetchCalls.length = 0;
  fetchText = VTT;
  translateImpl = async (texts, _from, to) =>
    texts.map((text) => `{${to}}${text.toUpperCase()}`);
});

describe("dropout VTT translation", () => {
  test("translates only cue text and keeps speakers and cue tags", async () => {
    expect(await translateVtt(VTT, "en", "ru", fakeTranslate)).toBe(
      TRANSLATED_VTT,
    );
    expect(translateCalls).toHaveLength(1);
    expect(translateCalls[0].texts).toEqual([
      "Hello __VOTDROPOUTTAG0__world__VOTDROPOUTTAG1__",
      "okay",
      "What?",
      "Yes.",
      "__VOTDROPOUTTAG0__plain__VOTDROPOUTTAG1__ text",
    ]);
  });

  test("keeps CRLF line endings", async () => {
    expect(
      await translateVtt(
        VTT.replaceAll("\n", "\r\n"),
        "en",
        "ru",
        fakeTranslate,
      ),
    ).toBe(TRANSLATED_VTT.replaceAll("\n", "\r\n"));
  });

  test("splits long subtitles into batches", async () => {
    const cues = Array.from({ length: 40 }, (_, i) => {
      const time = `00:00:${String(i).padStart(2, "0")}`;
      return `${time}.000 --> ${time}.500\n${"word ".repeat(80)}${i}\n`;
    });
    await translateVtt(
      `WEBVTT\n\n${cues.join("\n")}`,
      "en",
      "ru",
      fakeTranslate,
    );
    expect(translateCalls.map((call) => call.texts.length)).toEqual([
      18, 18, 4,
    ]);
  });

  test("returns undefined when nothing was translated", async () => {
    translateImpl = async (texts) => texts;
    expect(await translateVtt(VTT, "en", "ru", fakeTranslate)).toBeUndefined();
    expect(
      await translateVtt("WEBVTT\n\n", "en", "ru", fakeTranslate),
    ).toBeUndefined();
  });
});

describe("dropout translated subtitles track", () => {
  test("creates a local track from english vimeo subtitles", async () => {
    const videoData = {
      subtitles: [
        vimeoSubtitle("de", "https://captions.vimeo.com/de.vtt"),
        {
          ...vimeoSubtitle("en", "https://captions.vimeo.com/en.vtt"),
          isAutoGenerated: true,
        },
      ],
    };

    const [first, second] = await Promise.all([
      getTranslatedDropoutSubtitles(videoData, "ru", deps),
      getTranslatedDropoutSubtitles(videoData, "ru", deps),
    ]);
    expect(first).toEqual({
      source: "dropout",
      format: "vtt",
      language: "ru",
      translatedFromLanguage: "en",
      url: expect.stringMatching(/^vot-dropout-subtitles:\d+$/),
      isAutoGenerated: true,
    });
    expect(second).toBe(first);
    expect(fetchCalls).toEqual(["https://captions.vimeo.com/en.vtt"]);
    expect(getLocalDropoutSubtitles(first?.url ?? "")).toBe(TRANSLATED_VTT);
  });

  test("skips same language and missing vimeo subtitles", async () => {
    const videoData = {
      subtitles: [vimeoSubtitle("en", "https://captions.vimeo.com/en2.vtt")],
    };
    expect(
      await getTranslatedDropoutSubtitles(videoData, "en", deps),
    ).toBeNull();
    expect(
      await getTranslatedDropoutSubtitles({ subtitles: [] }, "ru", deps),
    ).toBe(null);
    expect(fetchCalls).toEqual([]);
  });

  test("retries after a failed translation", async () => {
    const videoData = {
      subtitles: [vimeoSubtitle("en", "https://captions.vimeo.com/bad.vtt")],
    };
    fetchText = "<html>not a subtitle</html>";
    expect(
      await getTranslatedDropoutSubtitles(videoData, "ru", deps),
    ).toBeNull();
    fetchText = VTT;
    expect(
      await getTranslatedDropoutSubtitles(videoData, "ru", deps),
    ).not.toBeNull();
    expect(fetchCalls).toHaveLength(2);
  });

  test("ignores urls that are not local tracks", () => {
    expect(getLocalDropoutSubtitles("https://captions.vimeo.com/en.vtt")).toBe(
      undefined,
    );
    expect(getLocalDropoutSubtitles("vot-dropout-subtitles:999")).toBe(
      undefined,
    );
  });
});
