import type { SubtitleLine, SubtitleToken } from "../types/subtitles";
import { segmentSentences } from "./segmenter";
import { shouldInsertSpaceBetweenTextFragments } from "./textSpacing";

type NormalizedLineSpan = {
  line: SubtitleLine;
  text: string;
  start: number;
  end: number;
};

const WHITESPACE_RE = /\s/u;

const hasVisibleText = (value: string): boolean => Boolean(value.trim());

const buildNormalizedLineSpans = (
  lines: readonly SubtitleLine[],
): {
  streamText: string;
  spans: NormalizedLineSpan[];
} => {
  let streamText = "";
  let previousText = "";
  const spans: NormalizedLineSpan[] = [];

  for (const line of lines) {
    const normalizedText = line.text.trim();
    if (!normalizedText) continue;

    if (
      streamText &&
      shouldInsertSpaceBetweenTextFragments(previousText, normalizedText)
    ) {
      streamText += " ";
    }

    const start = streamText.length;
    streamText += normalizedText;
    const end = streamText.length;

    spans.push({
      line: {
        ...line,
        text: normalizedText,
      },
      text: normalizedText,
      start,
      end,
    });
    previousText = normalizedText;
  }

  return { streamText, spans };
};

const trimSentenceRange = (
  streamText: string,
  start: number,
  end: number,
): {
  start: number;
  end: number;
} | null => {
  let trimmedStart = start;
  let trimmedEnd = end;

  while (
    trimmedStart < trimmedEnd &&
    WHITESPACE_RE.test(streamText[trimmedStart] ?? "")
  ) {
    trimmedStart += 1;
  }

  while (
    trimmedEnd > trimmedStart &&
    WHITESPACE_RE.test(streamText[trimmedEnd - 1] ?? "")
  ) {
    trimmedEnd -= 1;
  }

  if (trimmedStart >= trimmedEnd) {
    return null;
  }

  return {
    start: trimmedStart,
    end: trimmedEnd,
  };
};

const sliceLineToken = (
  span: NormalizedLineSpan,
  rangeStart: number,
  rangeEnd: number,
): SubtitleToken | null => {
  const overlapStart = Math.max(rangeStart, span.start);
  const overlapEnd = Math.min(rangeEnd, span.end);
  if (overlapStart >= overlapEnd) {
    return null;
  }

  const localStart = overlapStart - span.start;
  const localEnd = overlapEnd - span.start;
  const text = span.text.slice(localStart, localEnd);
  if (!text) {
    return null;
  }

  const textLength = Math.max(span.text.length, 1);
  const startMs =
    span.line.startMs +
    Math.round((span.line.durationMs * localStart) / textLength);
  const endMs =
    span.line.startMs +
    Math.round((span.line.durationMs * localEnd) / textLength);

  return {
    text,
    startMs,
    durationMs: Math.max(0, endMs - startMs),
    isWordLike: hasVisibleText(text),
  };
};

const buildSentenceLine = (
  streamText: string,
  spans: readonly NormalizedLineSpan[],
  segment: {
    text: string;
    index: number;
  },
): SubtitleLine | null => {
  const rawStart = segment.index;
  const rawEnd = rawStart + segment.text.length;
  const trimmedRange = trimSentenceRange(streamText, rawStart, rawEnd);
  if (!trimmedRange) {
    return null;
  }

  const text = streamText.slice(trimmedRange.start, trimmedRange.end);
  if (!hasVisibleText(text)) {
    return null;
  }

  const tokens: SubtitleToken[] = [];
  let speakerId = "0";

  for (const span of spans) {
    const token = sliceLineToken(span, trimmedRange.start, trimmedRange.end);
    if (!token) continue;

    if (tokens.length === 0) {
      speakerId = span.line.speakerId;
    }
    tokens.push(token);
  }

  if (!tokens.length) {
    return null;
  }

  const startMs = Math.min(...tokens.map((token) => token.startMs));
  const endMs = Math.max(
    ...tokens.map((token) => token.startMs + Math.max(0, token.durationMs)),
  );

  return {
    text,
    startMs,
    durationMs: Math.max(0, endMs - startMs),
    speakerId,
    tokens,
  };
};

export const mergeAutoGeneratedSubtitleLines = (
  lines: readonly SubtitleLine[],
  locale?: string,
): SubtitleLine[] => {
  const { streamText, spans } = buildNormalizedLineSpans(lines);
  if (!streamText || !spans.length) {
    return [];
  }

  const segments = segmentSentences(streamText, locale);
  const sentenceLines = segments
    .map((segment) => buildSentenceLine(streamText, spans, segment))
    .filter((line): line is SubtitleLine => line !== null);

  return sentenceLines.length ? sentenceLines : spans.map(({ line }) => line);
};
