import type { VideoService } from "@vot.js/core/types/service";
import type {
  GetSubtitlesResponse,
  VideoSubtitlesOpts,
} from "@vot.js/core/types/yandex";

export type SubtitleToken = {
  text: string;
  startMs: number;
  durationMs: number;
  isWordLike: boolean;
};

export type SubtitleLine = {
  text: string;
  startMs: number;
  durationMs: number;
  speakerId: string;
  tokens: SubtitleToken[];
};

export type ProcessedSubtitles = {
  subtitles: SubtitleLine[];
};

export type SubtitleDescriptor = {
  source: string;
  format: "srt" | "vtt" | "json";
  language: string;
  url: string;
  translatedFromLanguage?: string;
  isAutoGenerated?: boolean;
};

export type VideoDataForSubtitles = {
  host: string;
  url: string;
  detectedLanguage: string;
  videoId: string;
  duration: number;
  subtitles?: SubtitleDescriptor[];
};

export type SubtitlesRequestPayload = VideoSubtitlesOpts<VideoService>;
export type SubtitlesResponsePayload = GetSubtitlesResponse;

export interface SubtitlesClient {
  getSubtitles(
    args: SubtitlesRequestPayload,
  ): Promise<SubtitlesResponsePayload>;
}
