import type { SubtitleDescriptor } from "../types/subtitles";
import {
  type BuiltInSubtitleFontFamily,
  type SubtitleFormat,
  subtitleFontFamilies,
  subtitleFormats,
} from "../types/subtitles";

const subtitleFormatsSet = new Set(subtitleFormats);

function isSubtitleFormat(value: unknown): value is SubtitleFormat {
  return (
    typeof value === "string" && subtitleFormatsSet.has(value as SubtitleFormat)
  );
}

function isRecord(value: unknown): value is Record<string, unknown> {
  return value !== null && typeof value === "object";
}

export function parseSubtitleDescriptor(
  value: unknown,
): SubtitleDescriptor | null {
  if (!isRecord(value)) {
    return null;
  }

  const format = value.format;
  if (
    typeof value.source !== "string" ||
    typeof value.language !== "string" ||
    typeof value.url !== "string" ||
    !isSubtitleFormat(format)
  ) {
    return null;
  }

  return {
    source: value.source,
    format,
    language: value.language,
    url: value.url,
    translatedFromLanguage:
      typeof value.translatedFromLanguage === "string"
        ? value.translatedFromLanguage
        : undefined,
    isAutoGenerated:
      typeof value.isAutoGenerated === "boolean"
        ? value.isAutoGenerated
        : undefined,
  };
}

export function isBuiltInSubtitleFontFamily(
  fontFamily: string,
): fontFamily is BuiltInSubtitleFontFamily {
  return subtitleFontFamilies.includes(fontFamily as BuiltInSubtitleFontFamily);
}
