import type { VideoService } from "@vot.js/core/types/service";
import type {
  GetSubtitlesResponse,
  VideoSubtitlesOpts,
} from "@vot.js/core/types/yandex";

export const subtitleFormats = ["srt", "vtt", "ass", "json"] as const;
export type SubtitleFormat = (typeof subtitleFormats)[number];

export const subtitleFontFamilies = [
  "default-sans",
  "arial",
  "helvetica",
  "roboto",
  "verdana",
  "open-sans",
  "poppins",
  "lato",
  "montserrat",
  "barlow",
] as const;
export type BuiltInSubtitleFontFamily = (typeof subtitleFontFamilies)[number];
export type GoogleSubtitleFontFamily = `google:${string}`;
export type SubtitleFontFamily =
  | BuiltInSubtitleFontFamily
  | GoogleSubtitleFontFamily;

export const subtitleFontFamilyCss = {
  "default-sans": `"Roboto", "Segoe UI", system-ui, sans-serif`,
  arial: `Arial, "Helvetica Neue", Helvetica, sans-serif`,
  helvetica: `"Helvetica Neue", Helvetica, Arial, sans-serif`,
  roboto: `"Roboto", "Segoe UI", system-ui, sans-serif`,
  verdana: `Verdana, Geneva, sans-serif`,
  "open-sans": `"Open Sans", "Segoe UI", system-ui, sans-serif`,
  poppins: `"Poppins", "Segoe UI", system-ui, sans-serif`,
  lato: `"Lato", "Segoe UI", system-ui, sans-serif`,
  montserrat: `"Montserrat", "Segoe UI", system-ui, sans-serif`,
  barlow: `"Barlow", "Segoe UI", system-ui, sans-serif`,
} as const satisfies Record<BuiltInSubtitleFontFamily, string>;

export function isBuiltInSubtitleFontFamily(
  fontFamily: string,
): fontFamily is BuiltInSubtitleFontFamily {
  return subtitleFontFamilies.includes(fontFamily as BuiltInSubtitleFontFamily);
}

export const subtitlePositionPresets = [
  "bottom-center",
  "center",
  "top-center",
  "bottom-left",
  "bottom-right",
  "custom",
] as const;
export type SubtitlePositionPreset = (typeof subtitlePositionPresets)[number];

export type SubtitleInlineStyle = {
  italic?: boolean;
  bold?: boolean;
  underline?: boolean;
};

export type SubtitleToken = {
  text: string;
  startMs: number;
  durationMs: number;
  isWordLike: boolean;
  style?: SubtitleInlineStyle;
};

export type SubtitleCueKind = "cue" | "dialogue" | "comment";

export type WebVttCueSettings = {
  raw: string;
  values: Record<string, string>;
};

export type WebVttCueMetadata = {
  cueId?: string;
  settings?: WebVttCueSettings;
  voice?: string;
  rawPayload: string[];
};

export type AssCueMetadata = {
  kind: Exclude<SubtitleCueKind, "cue">;
  layer: string;
  style: string;
  name: string;
  marginL: string;
  marginR: string;
  marginV: string;
  effect: string;
  rawText: string;
  overrideTags: string[];
};

export type SubtitleLineMetadata = {
  rawText?: string;
  styledSpans?: SubtitleStyledSpan[];
  vtt?: WebVttCueMetadata;
  ass?: AssCueMetadata;
};

export type SubtitleStyledSpan = {
  start: number;
  end: number;
  style?: SubtitleInlineStyle;
};

export type SubtitleLine = {
  text: string;
  startMs: number;
  durationMs: number;
  speakerId: string;
  tokens: SubtitleToken[];
  metadata?: SubtitleLineMetadata;
};

export type WebVttDocumentBlock = {
  cueIndex: number;
  lines: string[];
};

export type WebVttDocumentMetadata = {
  headerText: string;
  blocks: WebVttDocumentBlock[];
};

export type AssDocumentMetadata = {
  scriptInfoLines: string[];
  styleFormat: string;
  styleLines: string[];
  eventFormat: string;
  preEventLines: string[];
  commentLines: string[];
};

export type ProcessedSubtitles = {
  format: SubtitleFormat;
  subtitles: SubtitleLine[];
  metadata?: {
    vtt?: WebVttDocumentMetadata;
    ass?: AssDocumentMetadata;
  };
};

export type SubtitleDescriptor = {
  source: string;
  format: SubtitleFormat;
  language: string;
  url: string;
  translatedFromLanguage?: string;
  isAutoGenerated?: boolean;
};

export type VideoDataForSubtitles = {
  host: string;
  url: string;
  detectedLanguage: string;
  videoId: string;
  duration: number;
  subtitles?: SubtitleDescriptor[];
};

export type SubtitlesRequestPayload = VideoSubtitlesOpts<VideoService>;
export type SubtitlesResponsePayload = GetSubtitlesResponse;

export interface SubtitlesClient {
  getSubtitles(
    args: SubtitlesRequestPayload,
  ): Promise<SubtitlesResponsePayload>;
}
