import YoutubeHelper from "@vot.js/ext/helpers/youtube";
import type { VideoHandler } from "../../index";
import { localizationProvider } from "../../localization/localizationProvider";
import { SubtitlesProcessor } from "../../subtitles/processor";
import type {
  SubtitleDescriptor,
  VideoDataForSubtitles,
} from "../../subtitles/types";
import debug from "../../utils/debug";
import { proxifyYandexSubtitlesUrl } from "./proxyShared";
import {
  buildSubtitlesSelectOptions,
  DISABLED_SUBTITLES_VALUE,
  getIndexedSubtitleDescriptors,
  getSelectedSubtitlesValue,
  getSubtitleDescriptorAtIndex,
  parseSubtitlesOptionIndex,
  pickBestSubtitlesIndex,
} from "./subtitlesShared";

export { resolveSubtitlesLanguage } from "./subtitlesShared";

const subtitlesSelectionRequestVersion = new WeakMap<VideoHandler, number>();

function getPreferredSubtitlesLanguage(
  handler: VideoHandler,
): string | undefined {
  const videoData = handler.videoData;
  return (
    handler.getPreferredSubtitlesLanguage(
      videoData?.detectedLanguage,
      videoData?.responseLanguage,
    ) ?? videoData?.responseLanguage ?? handler.translateToLang
  );
}

function getCacheDetectedLanguage(handler: VideoHandler): string | undefined {
  const videoData = handler.videoData;
  const detectedLanguage = videoData?.detectedLanguage?.toLowerCase();
  if (detectedLanguage && detectedLanguage !== "auto") {
    return detectedLanguage;
  }

  return videoData?.responseLanguage?.toLowerCase() ?? handler.translateToLang;
}

function getCurrentSubtitlesCacheKey(handler: VideoHandler): string | null {
  const videoData = handler.videoData;
  if (!videoData?.videoId) {
    return null;
  }

  const detectedLanguage = getCacheDetectedLanguage(handler);
  if (!detectedLanguage) {
    return null;
  }

  const subtitleLanguage = getPreferredSubtitlesLanguage(handler);
  if (!subtitleLanguage) {
    return null;
  }

  return handler.getSubtitlesCacheKey(
    videoData.videoId,
    detectedLanguage,
    subtitleLanguage,
  );
}

function buildSubtitleDescriptorKey(descriptor: SubtitleDescriptor): string {
  return [
    descriptor.source,
    descriptor.format,
    descriptor.language,
    descriptor.translatedFromLanguage ?? "",
    descriptor.isAutoGenerated ? "1" : "0",
    descriptor.url,
  ].join("|");
}

function dedupeSubtitles(
  subtitles: readonly SubtitleDescriptor[],
): SubtitleDescriptor[] {
  const seen = new Set<string>();
  const result: SubtitleDescriptor[] = [];

  for (const descriptor of subtitles) {
    const key = buildSubtitleDescriptorKey(descriptor);
    if (seen.has(key)) {
      continue;
    }

    seen.add(key);
    result.push(descriptor);
  }

  return result;
}

function enrichYoutubeSubtitlesForPreference(
  handler: VideoHandler,
  subtitleLanguage: string,
): VideoDataForSubtitles {
  const videoData = handler.videoData;
  if (!videoData) {
    throw new Error("Video data is required to load subtitles");
  }

  if (handler.site.host !== "youtube" || !subtitleLanguage) {
    return videoData;
  }

  const preferredYoutubeSubtitles =
    YoutubeHelper.getSubtitles(subtitleLanguage);
  if (!preferredYoutubeSubtitles.length) {
    return videoData;
  }

  return {
    ...videoData,
    subtitles: dedupeSubtitles([
      ...(Array.isArray(videoData.subtitles) ? videoData.subtitles : []),
      ...preferredYoutubeSubtitles,
    ]),
  };
}

function nextSubtitlesSelectionRequestVersion(handler: VideoHandler): number {
  const nextVersion = (subtitlesSelectionRequestVersion.get(handler) ?? 0) + 1;
  subtitlesSelectionRequestVersion.set(handler, nextVersion);
  return nextVersion;
}

function isCurrentSubtitlesSelectionRequest(
  handler: VideoHandler,
  requestVersion: number,
): boolean {
  return subtitlesSelectionRequestVersion.get(handler) === requestVersion;
}

function clearSelectedSubtitles(
  handler: VideoHandler,
  overlayView: NonNullable<VideoHandler["uiManager"]["votOverlayView"]>,
): VideoHandler {
  if (handler.hasSubtitlesWidget()) {
    handler.subtitlesWidget?.setContent(null);
  }
  overlayView.downloadSubtitlesButton.hidden = true;
  handler.yandexSubtitles = null;
  return handler;
}

export async function changeSubtitlesLang(
  this: VideoHandler,
  subs: string,
): Promise<VideoHandler> {
  debug.log("[onchange] subtitles", subs);
  const requestVersion = nextSubtitlesSelectionRequestVersion(this);
  const overlayView = this.uiManager.votOverlayView;
  if (!overlayView?.subtitlesSelect || !overlayView.downloadSubtitlesButton) {
    return this;
  }
  overlayView.subtitlesSelect.setSelectedValue(subs);
  if (subs === DISABLED_SUBTITLES_VALUE) {
    return clearSelectedSubtitles(this, overlayView);
  }

  const subtitlesIndex = parseSubtitlesOptionIndex(subs);
  if (subtitlesIndex == null) {
    return clearSelectedSubtitles(this, overlayView);
  }

  const descriptor = getSubtitleDescriptorAtIndex(
    this.subtitles,
    subtitlesIndex,
  );
  if (!descriptor) {
    return clearSelectedSubtitles(this, overlayView);
  }

  let subtitlesObj: SubtitleDescriptor = { ...descriptor };
  const proxiedSubtitlesUrl = proxifyYandexSubtitlesUrl(subtitlesObj.url, {
    translateProxyEnabled: this.data?.translateProxyEnabled,
    proxyWorkerHost: this.data?.proxyWorkerHost,
  });
  if (proxiedSubtitlesUrl !== subtitlesObj.url) {
    subtitlesObj = {
      ...subtitlesObj,
      url: proxiedSubtitlesUrl,
    };
    console.log(`[VOT] Subs proxied via ${subtitlesObj.url}`);
  }

  const fetchedSubtitles =
    await SubtitlesProcessor.fetchSubtitles(subtitlesObj);
  if (!isCurrentSubtitlesSelectionRequest(this, requestVersion)) {
    return this;
  }

  this.yandexSubtitles = fetchedSubtitles;
  this.getSubtitlesWidget().setContent(
    this.yandexSubtitles,
    subtitlesObj.language,
  );
  overlayView.downloadSubtitlesButton.hidden = false;
  return this;
}

export async function updateSubtitlesLangSelect(this: VideoHandler) {
  const overlayView = this.uiManager.votOverlayView;
  if (!overlayView?.subtitlesSelect) {
    return;
  }

  const subtitleDescriptors = getIndexedSubtitleDescriptors(this.subtitles);
  const updatedOptions = buildSubtitlesSelectOptions(subtitleDescriptors);
  overlayView.subtitlesSelect.updateItems(updatedOptions);
  await this.changeSubtitlesLang(DISABLED_SUBTITLES_VALUE);
}

export async function ensureSubtitlesForCurrentLangPair(this: VideoHandler) {
  const cacheKey = getCurrentSubtitlesCacheKey(this);

  if (!cacheKey) {
    if (this.subtitlesCacheKey !== null || this.subtitles.length > 0) {
      this.subtitles = [];
      this.subtitlesCacheKey = null;
      await this.updateSubtitlesLangSelect();
    }
    return this;
  }

  if (this.subtitlesCacheKey === cacheKey) {
    const hasCachedSubtitles =
      this.cacheManager.getSubtitles(cacheKey) !== undefined;
    if (this.subtitles.length > 0 || hasCachedSubtitles) {
      return this;
    }
  }

  const cachedSubs = this.cacheManager.getSubtitles(cacheKey);
  if (cachedSubs !== undefined) {
    this.subtitles = Array.isArray(cachedSubs) ? cachedSubs : [];
    this.subtitlesCacheKey = cacheKey;
    await this.updateSubtitlesLangSelect();
    return this;
  }

  await this.loadSubtitles();
  return this;
}

/**
 * Hotkey/helper: enables subtitles for the currently selected language pair.
 *
 * If an exact "from -> to" subtitles track is unavailable, falls back to any
 * subtitles track in the target language.
 * For same-language pair (from == to), prefer site subtitles before Yandex.
 */
export async function enableSubtitlesForCurrentLangPair(this: VideoHandler) {
  const overlayView = this.uiManager.votOverlayView;
  if (!overlayView?.subtitlesSelect) return this;

  try {
    await ensureSubtitlesForCurrentLangPair.call(this);
  } catch {
    // If loading fails, we can't enable anything.
    return this;
  }

  const fromLang = (this.videoData?.detectedLanguage ??
    this.translateFromLang) as string;
  const toLang = getPreferredSubtitlesLanguage(this);
  if (!toLang) {
    return this;
  }

  const bestIdx = pickBestSubtitlesIndex(
    getIndexedSubtitleDescriptors(this.subtitles),
    fromLang,
    toLang,
  );
  if (bestIdx == null) {
    return this;
  }

  // If the currently selected subtitles already match the chosen track, do nothing.
  const currentValue = getSelectedSubtitlesValue(
    overlayView.subtitlesSelect.selectedValues,
  );
  if (currentValue === String(bestIdx)) {
    return this;
  }

  await this.changeSubtitlesLang(String(bestIdx));
  return this;
}

/**
 * Re-evaluates the active subtitles track for the currently selected language
 * pair, but only when auto-subtitles are enabled.
 */
export async function refreshAutoSubtitlesForCurrentLangPair(
  this: VideoHandler,
) {
  if (!this.data?.autoSubtitles || !this.videoData?.videoId) {
    return this;
  }

  await this.enableSubtitlesForCurrentLangPair();
  return this;
}

/**
 * Hotkey helper: toggles subtitles.
 *
 * - If subtitles are currently enabled (any non-"disabled" value), disable them.
 * - If subtitles are disabled, enable the best subtitles for the current
 *   language pair.
 */
export async function toggleSubtitlesForCurrentLangPair(this: VideoHandler) {
  const overlayView = this.uiManager.votOverlayView;
  if (!overlayView?.subtitlesSelect) return this;

  const currentValue = getSelectedSubtitlesValue(
    overlayView.subtitlesSelect.selectedValues,
  );

  if (currentValue && currentValue !== DISABLED_SUBTITLES_VALUE) {
    await this.changeSubtitlesLang(DISABLED_SUBTITLES_VALUE);
    return this;
  }

  await this.enableSubtitlesForCurrentLangPair();
  return this;
}

export async function loadSubtitles(this: VideoHandler) {
  if (!this.videoData?.videoId) {
    console.error(
      `[VOT] ${localizationProvider.getDefault("VOTNoVideoIDFound")}`,
    );
    this.subtitles = [];
    this.subtitlesCacheKey = null;
    return;
  }

  const subtitleLanguage = getPreferredSubtitlesLanguage(this);
  if (!subtitleLanguage) {
    this.subtitles = [];
    this.subtitlesCacheKey = null;
    await this.updateSubtitlesLangSelect();
    return;
  }

  const cacheKey = this.getSubtitlesCacheKey(
    this.videoData.videoId,
    this.videoData.detectedLanguage,
    subtitleLanguage,
  );
  try {
    let cachedSubs = this.cacheManager.getSubtitles(cacheKey);
    if (!cachedSubs) {
      // Deduplicate concurrent requests for the same key (e.g. when user spams
      // the subtitles hotkey before the first request resolves).
      let inflight = this.subtitlesLoadPromises.get(cacheKey);
      if (inflight === undefined) {
        const videoDataForSubtitles = enrichYoutubeSubtitlesForPreference(
          this,
          subtitleLanguage,
        );
        inflight = SubtitlesProcessor.getSubtitles(
          this.votClient,
          videoDataForSubtitles,
        );
        this.subtitlesLoadPromises.set(cacheKey, inflight);
      }

      try {
        cachedSubs = await inflight;
        cachedSubs = Array.isArray(cachedSubs) ? cachedSubs : [];
        this.cacheManager.setSubtitles(cacheKey, cachedSubs);
      } finally {
        // Only clear if we're still pointing at the same promise.
        if (this.subtitlesLoadPromises.get(cacheKey) === inflight) {
          this.subtitlesLoadPromises.delete(cacheKey);
        }
      }
    }
    this.subtitles = Array.isArray(cachedSubs) ? cachedSubs : [];
    this.subtitlesCacheKey = cacheKey;
  } catch (error) {
    console.error("[VOT] Failed to load subtitles:", error);
    this.subtitles = [];
    this.subtitlesCacheKey = null;
  }
  await this.updateSubtitlesLangSelect();
}
