import { localizationProvider } from "../../localization/localizationProvider";
import {
  parseSubtitleDescriptor,
  type SubtitleDescriptor,
} from "../../subtitles/types";
import {
  type ResponseLanguageSubtitles,
  subtitleResponseLanguageModes,
} from "../../types/storage";

export type IndexedSubtitleDescriptor = {
  descriptor: SubtitleDescriptor;
  index: number;
};

export type SubtitlesSelectOption = {
  label: string;
  value: string;
  selected: boolean;
  disabled: boolean;
};

export const DISABLED_SUBTITLES_VALUE = "disabled";
const SUBTITLES_INDEX_OPTION_PATTERN = /^\d+$/u;
const [AUTO_SUBTITLE_LANGUAGE_VALUE, ORIGINAL_SUBTITLE_LANGUAGE_VALUE] =
  subtitleResponseLanguageModes;

export function getIndexedSubtitleDescriptors(
  subtitles: readonly unknown[],
): IndexedSubtitleDescriptor[] {
  const descriptors: IndexedSubtitleDescriptor[] = [];

  for (let index = 0; index < subtitles.length; index += 1) {
    const descriptor = parseSubtitleDescriptor(subtitles[index]);
    if (!descriptor) {
      continue;
    }

    descriptors.push({
      descriptor,
      index,
    });
  }

  return descriptors;
}

export function parseSubtitlesOptionIndex(value: string): number | null {
  if (!SUBTITLES_INDEX_OPTION_PATTERN.test(value)) {
    return null;
  }

  const parsed = Number(value);
  if (!Number.isSafeInteger(parsed)) {
    return null;
  }

  return parsed;
}

export function getSubtitleDescriptorAtIndex(
  subtitles: readonly unknown[],
  index: number,
): SubtitleDescriptor | null {
  if (!Number.isInteger(index) || index < 0 || index >= subtitles.length) {
    return null;
  }

  return parseSubtitleDescriptor(subtitles[index]);
}

function createDisabledSubtitlesOption(): SubtitlesSelectOption {
  return {
    label: localizationProvider.get("VOTSubtitlesDisabled"),
    value: DISABLED_SUBTITLES_VALUE,
    selected: true,
    disabled: false,
  };
}

function buildSubtitleLabel(subtitle: SubtitleDescriptor): string {
  const languageLabel = localizationProvider.getLangLabel(subtitle.language);
  const translatedFromLabel = subtitle.translatedFromLanguage
    ? ` ${localizationProvider.get("VOTTranslatedFrom")} ${localizationProvider.getLangLabel(
        subtitle.translatedFromLanguage,
      )}`
    : "";
  const sourceSuffix =
    subtitle.source === "yandex" ? "" : `, ${globalThis.location.hostname}`;
  const autogeneratedSuffix = subtitle.isAutoGenerated
    ? ` (${localizationProvider.get("VOTAutogenerated")})`
    : "";

  return `${languageLabel}${translatedFromLabel}${sourceSuffix}${autogeneratedSuffix}`;
}

export function buildSubtitlesSelectOptions(
  subtitleDescriptors: readonly IndexedSubtitleDescriptor[],
): SubtitlesSelectOption[] {
  const options: SubtitlesSelectOption[] = [createDisabledSubtitlesOption()];

  for (const { descriptor, index } of subtitleDescriptors) {
    options.push({
      label: buildSubtitleLabel(descriptor),
      value: String(index),
      selected: false,
      disabled: false,
    });
  }

  return options;
}

export function getSelectedSubtitlesValue(
  selectedValues: Iterable<string>,
): string | undefined {
  const iterator = selectedValues[Symbol.iterator]();
  const first = iterator.next();
  return first.done ? undefined : first.value;
}

function normalizeLang(lang?: string): string {
  return (lang ?? "").toLowerCase();
}

function baseLang(lang?: string): string {
  const normalized = normalizeLang(lang);
  return normalized.split(/[-_]/)[0];
}

function langMatches(candidate?: string, desired?: string): boolean {
  if (!candidate || !desired) return false;
  const cand = normalizeLang(candidate);
  const want = normalizeLang(desired);
  return cand === want || baseLang(cand) === baseLang(want);
}

export function resolveSubtitlesLanguage(
  preference: ResponseLanguageSubtitles | undefined,
  detectedLanguage?: string,
  responseLanguage?: string,
): string | undefined {
  if (preference === ORIGINAL_SUBTITLE_LANGUAGE_VALUE) {
    const originalLanguage = normalizeLang(detectedLanguage);
    return originalLanguage && originalLanguage !== AUTO_SUBTITLE_LANGUAGE_VALUE
      ? originalLanguage
      : undefined;
  }

  if (
    typeof preference === "string" &&
    preference &&
    preference !== AUTO_SUBTITLE_LANGUAGE_VALUE
  ) {
    return normalizeLang(preference);
  }

  return normalizeLang(responseLanguage) || normalizeLang(detectedLanguage);
}

export function pickBestSubtitlesIndex(
  subtitles: readonly IndexedSubtitleDescriptor[],
  fromLang: string,
  toLang: string,
): number | null {
  if (!subtitles.length) return null;

  const from = normalizeLang(fromLang);
  const to = normalizeLang(toLang);
  const fromIsAuto = from === "auto" || from === "";
  const fromBase = baseLang(from);
  const toBase = baseLang(to);

  const isYandex = (descriptor: SubtitleDescriptor) =>
    descriptor.source === "yandex";
  const isAutoGenerated = (descriptor: SubtitleDescriptor) =>
    Boolean(descriptor.isAutoGenerated);
  const matchesPair = (
    descriptor: SubtitleDescriptor,
    wantFrom: string,
    wantTo: string,
  ) => {
    if (!langMatches(descriptor.language, wantTo)) return false;
    if (fromIsAuto) return true;
    return langMatches(descriptor.translatedFromLanguage, wantFrom);
  };
  const isSameLangOriginal = (descriptor: SubtitleDescriptor, lang: string) => {
    if (!langMatches(descriptor.language, lang)) return false;
    if (!descriptor.translatedFromLanguage) return true;
    return langMatches(descriptor.translatedFromLanguage, lang);
  };

  const find = (predicate: (descriptor: SubtitleDescriptor) => boolean) =>
    subtitles.find(({ descriptor }) => predicate(descriptor))?.index ?? null;
  const findOtherTarget = (): number | null => {
    const otherTargetManual = find(
      (descriptor) =>
        !isYandex(descriptor) &&
        langMatches(descriptor.language, to) &&
        !isAutoGenerated(descriptor),
    );
    if (otherTargetManual != null) return otherTargetManual;

    return find(
      (descriptor) =>
        !isYandex(descriptor) &&
        langMatches(descriptor.language, to) &&
        isAutoGenerated(descriptor),
    );
  };

  if (!fromIsAuto && fromBase && toBase && fromBase === toBase) {
    const nativeManual = find(
      (descriptor) =>
        isSameLangOriginal(descriptor, to) && !isAutoGenerated(descriptor),
    );
    if (nativeManual != null) return nativeManual;

    const nativeAuto = find(
      (descriptor) =>
        isSameLangOriginal(descriptor, to) && isAutoGenerated(descriptor),
    );
    if (nativeAuto != null) return nativeAuto;

    const otherTarget = findOtherTarget();
    if (otherTarget != null) return otherTarget;

    const yandexTargetSameLang = find(
      (descriptor) =>
        isYandex(descriptor) && langMatches(descriptor.language, to),
    );
    if (yandexTargetSameLang != null) return yandexTargetSameLang;
  }

  const yandexPair = find(
    (descriptor) => isYandex(descriptor) && matchesPair(descriptor, from, to),
  );
  if (yandexPair != null) return yandexPair;

  const yandexTarget = find(
    (descriptor) =>
      isYandex(descriptor) && langMatches(descriptor.language, to),
  );
  if (yandexTarget != null) return yandexTarget;

  const otherPair = find(
    (descriptor) => !isYandex(descriptor) && matchesPair(descriptor, from, to),
  );
  if (otherPair != null) return otherPair;

  const otherTarget = findOtherTarget();
  if (otherTarget != null) return otherTarget;

  return null;
}
