import YoutubeHelper from "@vot.js/ext/helpers/youtube";
import { getVideoData } from "@vot.js/ext/utils/videoData";
import votConfig from "@vot.js/shared/config";
import { availableLangs } from "@vot.js/shared/consts";
import type { RequestLang, ResponseLang } from "@vot.js/shared/types/data";

import type { VideoHandler } from "..";
import { localizationProvider } from "../localization/localizationProvider";
import debug from "../utils/debug";
import { GM_fetch } from "../utils/gm";
import { cleanText } from "../utils/text";
import { detect } from "../utils/translateApis";
import VOTLocalizedError from "../utils/VOTLocalizedError";
import {
  snapVolume01,
  volume01ToPercent,
} from "../utils/volume";
import type { VideoData as RuntimeVideoData } from "../videoHandler/shared";
import { isExternalVolumeHost } from "./hostPolicies";

const FORCED_DETECTED_LANGUAGE_BY_HOST: Record<string, RequestLang> = {
  rutube: "ru",
  "ok.ru": "ru",
  mail_ru: "ru",
  weverse: "ko",
  niconico: "ja",
  youku: "zh",
  bilibili: "zh",
  weibo: "zh",
  zdf: "de",
};

const MIN_DETECT_TEXT_LENGTH = 35;
const MAX_SHARED_LANGUAGE_STATES = 500;
const REQUEST_LANG_SET = new Set<RequestLang>(
  availableLangs as readonly RequestLang[],
);

type ResolvedRequestLang = Exclude<RequestLang, "auto">;
type SharedLanguageState = {
  detectInFlight?: Promise<ResolvedRequestLang | undefined>;
  detectedLanguage?: ResolvedRequestLang;
  userLanguageOverride?: ResolvedRequestLang;
  lastLoggedDetectedLanguage?: RequestLang;
  lastLoggedLangPair?: string;
};

type ResolveDetectedLanguageOptions = {
  isStream: boolean;
  host: string;
  possibleLanguage: unknown;
  subtitles?: unknown;
  userOverrideLanguage?: ResolvedRequestLang;
  cachedDetectedLanguage?: ResolvedRequestLang;
  title: unknown;
  description: unknown;
  allowTextLanguageDetection?: boolean;
  detectLanguage(text: string): Promise<ResolvedRequestLang | undefined>;
};

type ResolveDetectedLanguageResult = {
  detectedLanguage: RequestLang;
  cacheLanguage?: ResolvedRequestLang;
};

/**
 * Shared language caches across VideoManager instances within one frame.
 *
 * YouTube Shorts can transiently create multiple video handlers while the URL
 * (and therefore resolved `videoId`) still points to the same active short.
 * Per-instance caches are insufficient in that case and can trigger duplicate
 * language detection requests.
 */
const sharedLanguageStateByVideoId = new Map<string, SharedLanguageState>();

function getSharedLanguageState(videoId: string): SharedLanguageState {
  const cachedState = sharedLanguageStateByVideoId.get(videoId);
  if (cachedState) {
    return cachedState;
  }

  const createdState: SharedLanguageState = {};
  sharedLanguageStateByVideoId.set(videoId, createdState);
  while (sharedLanguageStateByVideoId.size > MAX_SHARED_LANGUAGE_STATES) {
    const oldestVideoId = sharedLanguageStateByVideoId.keys().next().value;
    if (typeof oldestVideoId !== "string") {
      break;
    }
    sharedLanguageStateByVideoId.delete(oldestVideoId);
  }
  return createdState;
}

function normalizeToRequestLang(value: unknown): RequestLang | undefined {
  if (typeof value !== "string") return undefined;
  const normalized = value.toLowerCase().split(/[-_]/)[0] as RequestLang;
  return REQUEST_LANG_SET.has(normalized) ? normalized : undefined;
}

function isResolvedLanguage(
  value: RequestLang | undefined,
): value is ResolvedRequestLang {
  return Boolean(value && value !== "auto");
}

function buildDetectText(title: unknown, description: unknown): string {
  const textTitle = typeof title === "string" ? title : "";
  const textDescription =
    typeof description === "string" ? description : undefined;
  return cleanText(textTitle, textDescription);
}

function resolveHostDetectedLanguage(host: string): RequestLang | undefined {
  const forcedDetectedLanguage = FORCED_DETECTED_LANGUAGE_BY_HOST[host];
  if (forcedDetectedLanguage) {
    return forcedDetectedLanguage;
  }

  if (host === "vk") {
    const trackLang = document.getElementsByTagName("track")?.[0]?.srclang;
    return normalizeToRequestLang(trackLang);
  }

  return undefined;
}

function resolveYoutubeDetectedLanguageFromSubtitles(
  subtitles: unknown,
): RequestLang | undefined {
  if (!Array.isArray(subtitles) || subtitles.length === 0) {
    return undefined;
  }

  const pickLanguage = (preferManual: boolean): RequestLang | undefined => {
    for (const subtitle of subtitles) {
      if (!subtitle || typeof subtitle !== "object") {
        continue;
      }

      const candidate = subtitle as {
        source?: unknown;
        language?: unknown;
        translatedFromLanguage?: unknown;
        isAutoGenerated?: unknown;
      };
      if (candidate.source !== "youtube") {
        continue;
      }
      if (typeof candidate.translatedFromLanguage === "string") {
        continue;
      }
      if (preferManual && candidate.isAutoGenerated === true) {
        continue;
      }

      const language = normalizeToRequestLang(candidate.language);
      if (isResolvedLanguage(language)) {
        return language;
      }
    }

    return undefined;
  };

  return pickLanguage(true) ?? pickLanguage(false);
}

export async function resolveDetectedLanguageForVideo(
  options: ResolveDetectedLanguageOptions,
): Promise<ResolveDetectedLanguageResult> {
  if (options.isStream) {
    return { detectedLanguage: "auto" };
  }

  if (options.userOverrideLanguage) {
    return { detectedLanguage: options.userOverrideLanguage };
  }

  const hostDetectedLanguage = resolveHostDetectedLanguage(options.host);
  if (isResolvedLanguage(hostDetectedLanguage)) {
    return {
      detectedLanguage: hostDetectedLanguage,
      cacheLanguage: hostDetectedLanguage,
    };
  }

  const normalizedPossibleLanguage = normalizeToRequestLang(
    options.possibleLanguage,
  );
  if (isResolvedLanguage(normalizedPossibleLanguage)) {
    return {
      detectedLanguage: normalizedPossibleLanguage,
      cacheLanguage: normalizedPossibleLanguage,
    };
  }

  const youtubeSubtitleDetectedLanguage =
    options.host === "youtube"
      ? resolveYoutubeDetectedLanguageFromSubtitles(options.subtitles)
      : undefined;
  if (isResolvedLanguage(youtubeSubtitleDetectedLanguage)) {
    return {
      detectedLanguage: youtubeSubtitleDetectedLanguage,
      cacheLanguage: youtubeSubtitleDetectedLanguage,
    };
  }

  if (options.cachedDetectedLanguage) {
    return { detectedLanguage: options.cachedDetectedLanguage };
  }

  if (!options.allowTextLanguageDetection) {
    return { detectedLanguage: "auto" };
  }

  const text = buildDetectText(options.title, options.description);
  if (!text || text.length < MIN_DETECT_TEXT_LENGTH) {
    return { detectedLanguage: "auto" };
  }

  const detectedLanguage = await options.detectLanguage(text);
  if (!detectedLanguage) {
    return { detectedLanguage: "auto" };
  }

  return {
    detectedLanguage,
    cacheLanguage: detectedLanguage,
  };
}

export class VOTVideoManager {
  videoHandler: VideoHandler;

  constructor(videoHandler: VideoHandler) {
    this.videoHandler = videoHandler;
  }

  private setDetectedLanguageCache(
    videoId: string,
    language: ResolvedRequestLang,
  ): void {
    getSharedLanguageState(videoId).detectedLanguage = language;
  }

  rememberUserLanguageSelection(videoId: string, language: RequestLang): void {
    const normalizedLanguage = normalizeToRequestLang(language);
    if (!isResolvedLanguage(normalizedLanguage)) {
      // "auto" means no manual override for this video.
      const sharedLanguageState = sharedLanguageStateByVideoId.get(videoId);
      if (sharedLanguageState) {
        delete sharedLanguageState.userLanguageOverride;
      }
      return;
    }

    const sharedLanguageState = getSharedLanguageState(videoId);
    sharedLanguageState.userLanguageOverride = normalizedLanguage;
    sharedLanguageState.detectedLanguage = normalizedLanguage;
  }

  rememberDetectedLanguage(videoId: string, language: RequestLang): void {
    const normalizedLanguage = normalizeToRequestLang(language);
    if (!isResolvedLanguage(normalizedLanguage)) {
      return;
    }

    this.setDetectedLanguageCache(videoId, normalizedLanguage);

    if (this.videoHandler.videoData?.videoId === videoId) {
      this.videoHandler.videoData.detectedLanguage = normalizedLanguage;
    }
  }

  private async detectLanguageSingleFlight(
    videoId: string,
    text: string,
  ): Promise<ResolvedRequestLang | undefined> {
    const sharedLanguageState = getSharedLanguageState(videoId);
    const inFlightDetect = sharedLanguageState.detectInFlight;
    if (inFlightDetect !== undefined) {
      return inFlightDetect;
    }

    const task: Promise<ResolvedRequestLang | undefined> = (async () => {
      debug.log(`Detecting language text: ${text}`);
      const language = normalizeToRequestLang(await detect(text));
      return isResolvedLanguage(language) ? language : undefined;
    })();

    sharedLanguageState.detectInFlight = task;
    try {
      return await task;
    } finally {
      if (sharedLanguageState.detectInFlight === task) {
        delete sharedLanguageState.detectInFlight;
      }
    }
  }

  async ensureDetectedLanguageForTranslation(
    videoData: RuntimeVideoData | undefined,
  ): Promise<void> {
    if (!videoData?.videoId || videoData.detectedLanguage !== "auto") {
      return;
    }

    const sharedLanguageState = getSharedLanguageState(videoData.videoId);
    const { detectedLanguage, cacheLanguage } =
      await resolveDetectedLanguageForVideo({
        isStream: videoData.isStream,
        host: this.videoHandler.site.host,
        possibleLanguage: videoData.detectedLanguage,
        subtitles: videoData.subtitles,
        userOverrideLanguage: sharedLanguageState.userLanguageOverride,
        cachedDetectedLanguage: sharedLanguageState.detectedLanguage,
        title: videoData.title,
        description: videoData.description,
        allowTextLanguageDetection: true,
        detectLanguage: async (text) =>
          await this.detectLanguageSingleFlight(videoData.videoId, text),
      });

    if (cacheLanguage) {
      this.setDetectedLanguageCache(videoData.videoId, cacheLanguage);
    }

    if (!detectedLanguage || detectedLanguage === "auto") {
      return;
    }

    this.videoHandler.setSelectMenuValues(
      detectedLanguage,
      this.videoHandler.translateToLang,
    );
  }

  async getVideoData() {
    const {
      duration,
      url,
      videoId,
      host,
      title,
      translationHelp = null,
      localizedTitle,
      description,
      detectedLanguage: possibleLanguage,
      subtitles,
      isStream = false,
    } = await getVideoData(this.videoHandler.site, {
      fetchFn: GM_fetch,
      video: this.videoHandler.video,
      language: localizationProvider.lang,
    });

    const sharedLanguageState = getSharedLanguageState(videoId);
    const { detectedLanguage, cacheLanguage } =
      await resolveDetectedLanguageForVideo({
        isStream,
        host: this.videoHandler.site.host,
        possibleLanguage,
        subtitles,
        userOverrideLanguage: sharedLanguageState.userLanguageOverride,
        cachedDetectedLanguage: sharedLanguageState.detectedLanguage,
        title,
        description,
        allowTextLanguageDetection: false,
        detectLanguage: async (text) =>
          await this.detectLanguageSingleFlight(videoId, text),
      });

    if (cacheLanguage) {
      this.setDetectedLanguageCache(videoId, cacheLanguage);
    }

    const videoData = {
      translationHelp,
      isStream,
      duration:
        duration ||
        this.videoHandler.video?.duration ||
        votConfig.defaultDuration, // if 0, we get 400 error
      videoId,
      url,
      host,
      detectedLanguage,
      responseLanguage: this.videoHandler.translateToLang,
      subtitles,
      title,
      localizedTitle,
      description,
      downloadTitle: localizedTitle ?? title ?? document.title ?? videoId,
    } satisfies RuntimeVideoData;

    if (sharedLanguageState.lastLoggedDetectedLanguage !== detectedLanguage) {
      console.log("[VOT] Detected language:", detectedLanguage);
      sharedLanguageState.lastLoggedDetectedLanguage = detectedLanguage;
    }
    return videoData;
  }

  async videoValidator() {
    const videoData = this.videoHandler.videoData;
    const data = this.videoHandler.data;
    if (!videoData || !data) {
      throw new VOTLocalizedError("VOTNoVideoIDFound");
    }

    debug.log("VideoValidator videoData: ", this.videoHandler.videoData);
    if (
      this.videoHandler.data.enabledDontTranslateLanguages &&
      this.videoHandler.data.dontTranslateLanguages?.includes(
        this.videoHandler.videoData.detectedLanguage,
      )
    ) {
      throw new VOTLocalizedError("VOTDisableFromYourLang");
    }

    if (this.videoHandler.videoData.isStream) {
      // Stream translation is disabled for all hosts.
      throw new VOTLocalizedError("VOTStreamNotAvailable");
    }

    if (this.videoHandler.videoData.duration > 14400) {
      throw new VOTLocalizedError("VOTVideoIsTooLong");
    }
    return true;
  }

  /**
   * Gets current video volume (0.0 - 1.0)
   */
  getVideoVolume() {
    const video = this.videoHandler.video;
    if (!video) return undefined;

    return snapVolume01(video.volume);
  }

  /**
   * Sets the video volume
   */
  setVideoVolume(volume: number) {
    const snapped = snapVolume01(volume);
    const shouldUnmute = snapped > 0;

    if (!isExternalVolumeHost(this.videoHandler.site.host)) {
      if (shouldUnmute) {
        this.videoHandler.video.muted = false;
      }
      this.videoHandler.video.volume = snapped;
      return this;
    }

    try {
      const player = YoutubeHelper.getPlayer() as
        | { unMute?: () => void }
        | undefined;
      YoutubeHelper.setVolume(snapped);
      if (shouldUnmute) {
        player?.unMute?.();
        this.videoHandler.video.muted = false;
      }
    } catch {
      // ignore - fall back to setting the HTMLMediaElement volume below.
    }

    if (shouldUnmute) {
      this.videoHandler.video.muted = false;
    }
    this.videoHandler.video.volume = snapped;
    return this;
  }

  /**
   * Checks if the video is muted
   */
  isMuted() {
    return isExternalVolumeHost(this.videoHandler.site.host)
      ? YoutubeHelper.isMuted()
      : this.videoHandler.video?.muted;
  }

  /**
   * Syncs the video volume slider with the actual video volume.
   */
  syncVideoVolumeSlider() {
    const overlayView = this.videoHandler.uiManager.votOverlayView;
    if (!overlayView?.isInitialized()) return this;

    const volumePercent = this.isMuted()
      ? 0
      : volume01ToPercent(this.getVideoVolume() ?? 0);

    overlayView.videoVolumeSlider.value = volumePercent;

    // Keep syncVolume delta state aligned with programmatic slider updates.
    this.videoHandler.onVideoVolumeSliderSynced?.(volumePercent);
    return this;
  }

  setSelectMenuValues(from: RequestLang, to: ResponseLang): this {
    const videoData = this.videoHandler.videoData;
    if (!videoData) {
      return this;
    }

    const normalizedFrom = normalizeToRequestLang(from) ?? "auto";
    const langPairLogKey = `${normalizedFrom}->${to}`;
    const sharedLanguageState = getSharedLanguageState(videoData.videoId);
    if (sharedLanguageState.lastLoggedLangPair !== langPairLogKey) {
      console.log(`[VOT] Set translation from ${normalizedFrom} to ${to}`);
      sharedLanguageState.lastLoggedLangPair = langPairLogKey;
    }
    videoData.detectedLanguage = normalizedFrom;
    videoData.responseLanguage = to;
    this.videoHandler.translateFromLang = normalizedFrom;
    this.videoHandler.translateToLang = to;

    const overlayView = this.videoHandler.uiManager.votOverlayView;
    if (!overlayView?.isInitialized()) {
      return this;
    }

    overlayView.languagePairSelect.fromSelect.selectTitle =
      localizationProvider.getLangLabel(normalizedFrom);
    overlayView.languagePairSelect.toSelect.selectTitle =
      localizationProvider.getLangLabel(to);
    overlayView.languagePairSelect.fromSelect.setSelectedValue(normalizedFrom);
    overlayView.languagePairSelect.toSelect.setSelectedValue(to);
    return this;
  }
}
